import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./layout/header";
import Footer from "./layout/footer";
import { CartProvider } from "./context/CartContext";
import CartIcon from "@/components/carticon";
// import { ClerkProvider } from "@clerk/nextjs";
// import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      // <ClerkProvider 
      // publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      // >
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <CartProvider> {/* Wrap the app in CartProvider */}
          <Header />
          {children}
          <CartIcon/>
          <Footer />
          {/* <CartDetails /> Render the client component here */}
        </CartProvider>
      </body>
    </html>
    // </ClerkProvider>
  );
}
